### ISSUE TITLE
Beautiful work!

### ISSUE THREAD

**Issue by aldopareja** [Holmeswww/AgentKit#4]
Wondering how hard would it be to leverage langchain to create one node, that enables changing the model being called at different points plus all of the other tools developed there.

**Comment by Holmeswww** [comment]
Hi,

  Each Node can take a custom compose prompt function. In our experiments, we actually mixed different LLM models for different nodes.

  You can also use langchain inside the node by using a custom compose function and LLM-querying function.

  For example, you can provide an LLM-query function that uses langchain instead of OpenAI.

  I wonder if this addresses your question.
